# This is a basic workflow to help you get started with Actions

name: Jordan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Jordan Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          Jordan Add other actions to build,
          Jordan test, and deploy your project.
      - name: Slash Commands
        uses: xt0rted/slash-command-action@v1.1.0
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.3.0
      - name: Jira Add Comment
        uses: atlassian/gajira-comment@v2.0.2
      - name: Cache
        uses: actions/cache@v2.1.4
          with: 
            # A list of files, directories, and wildcard patterns to cache and restore
            path: ./Jordan/
            # An explicit key for restoring and saving the cache
            key: 
            # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
      - name: Funny comments
        uses: Marta83/funny-comment-action@v2.1
      


      

